### ISSUE TITLE
Alternative loop with "exit on match" behavior

### ISSUE THREAD

**Issue by randomra** [m-ender/retina#24]
The regular `(` `)` loop exits if the string doesn't change in a loop. There could be another looping mechanism (marked by maybe `[` and `]`) which exits from the loop if the loop's last (or first) regex (the one in the `]`'s (or `[`'s) line) matches. This behavior would be similar to other languages do-while (or while-do) loops.

**Comment by mbuettner** [comment]
Since something like `([)]` doesn't make sense if `()` and `[]` are different constructs, maybe one could actually just make `[` and `]` special versions of `(` and `)` which add a termination condition. This means that `(]` would be do-while and `[)` would be while-do. Then you also get the weird `[]` (which is condition1, do, condition2, condition1, do, condition2,...), but I don't think that's a problem.

The main design decision is then whether any of these loops should *still* abort if there are no further changes in a single loop iteration, or whether these should allow infinite loops.

**Comment by m-ender** [comment]
A feature which effectively covers this has been implemented and will be released as part of Retina 1.0: a loop stage can now be given a regex parameter, and the loop will run as long as that regex matches. It's also possible to add the `^` ("reverse") option in which case the loop will run as long as that regex *doesn't* match. Examples:

```
/\d/+`^.

```

or 

```
/^a/^+`^.

```

against input `123abc` will give `abc`.
