### ISSUE TITLE
Example for Eval `~` stage?

### ISSUE THREAD

**Issue by mbomb007** [m-ender/retina#84]
I'm trying to figure out how to use History with Eval.

Take the program:

```retina
.

$+~K`ONE¶1
```

With input `SCONE`. 

The program first removes the input (I know it's redundant). Then, the constant stage sets the input to

```
ONE
1
```

I would expect Eval to use this constant as its sub-program, and with the configuration of `$+`, I would expect it to use the History of 0 (the program input) as its input. So I'm confused as to why the program doesn't replace the `ONE` in `SCONE` to create `SC1` for the output.

What am I doing wrong?

I think it'd be helpful if the [examples](https://github.com/m-ender/retina/blob/master/Examples/README.md) included an example using Eval and history like this, as so far I haven't figured it out from reading the docs and playing around.

https://tio.run/##K0otycxLNPz/X4@LS0W7zjvB38/10DYgP8ADyAIA

**Comment by m-ender** [comment]
Phew, it's been a hot minute since I've thought about Retina. I think the issue is that `$+` on its own is parsed as a loop stage and a "use substitution" configuration (which I think doesn't do anything in this case). You want a string option to access the history via a substitution, so `"$+"` should do the trick.

**Comment by mbomb007** [comment]
Ah, that was it! Thanks!

Yeah, I haven't used it for a while either. I rarely golf anymore. But I want to keep my knowledge of Retina, and I continue to use Retina or Retinate occasionally when I need advanced regex for something.
